# azure-pipelines-trigger.yml
name: SecondPipeline 

trigger: none

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: SecondPipeline   # Name of the pipeline resource
    source: parent # Name of the pipeline referenced by the pipeline resource
    trigger: true # enable the trigger

pool: 
  name: 'akpool'

steps:
  - script: echo This pipeline was set to be triggered after first pipeline completes.
